ALTER TABLE mcp_servers ADD COLUMN transport TEXT NOT NULL DEFAULT 'stdio';
ALTER TABLE mcp_servers ADD COLUMN command TEXT NOT NULL DEFAULT '';
ALTER TABLE mcp_servers ADD COLUMN url TEXT NOT NULL DEFAULT '';
ALTER TABLE mcp_servers ADD COLUMN headers TEXT NOT NULL DEFAULT '{}';
